BinduRestaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aboutus.urls')),
    path('', include('home.urls')),
    path('', include('contact.urls')),
    path('', include('blog.urls')),
    path('', include('meals.urls')),
    path('', include('reservation.urls')),
]

admin.site.site_header = "Restaurant AdminPanel"
admin.site.site_title = "Restaurant App Admin "
admin.site.site_index_title = "Welcome To Restaurant Admin Panel"

aboutus/urls.py
from django.urls import path
from . import views

app_name = 'aboutus'

urlpatterns = [
    path('', views.aboutus_list, name='aboutus'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('blog', views.post_list, name='post_list'),
    path('<int:id>', views.post_detail, name='post_detail'),
    path('tags=<slug:tag>', views.post_by_tag, name='post_by_tag'),
    path('category=<slug:category>', views.post_by_category, name='post_by_category'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
    path('c', views.send_email, name='c'),
    path('success', views.send_success, name='success'),
]

meals/urls.py
from django.urls import path
from . import views

app_name = 'meals'
urlpatterns = [
    path('meals', views.meal_list, name='meal_list'),
    #path('<slug:slug>', views.meal_detail, name='meal_detail')
]

reservation/urls.py
from django.urls import path
from . import views

app_name = 'reservation'
urlpatterns = [
    path('reserve_table', views.reserve_table, name='reserve_table'),
]

templates/base.html
{% load static %}
<html lang="en">
  <head>
    <title> Bindu || Restaurant </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:300,400,700,800|Open+Sans:300,400,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'site_static/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/owl.carousel.min.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/jquery.timepicker.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/fonts/fontawesome/css/font-awesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/fonts/flaticon/font/flaticon.css' %}">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'site_static/css/style.css' %}">
  </head>
  <body>

    <div class="site-wrap">

      <nav class="site-menu">
        <div class="site-menu-inner">
          <ul class="list-unstyled">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="{% url 'meals:meal_list' %}">Meals</a></li>
            <li><a href="{% url 'aboutus:aboutus' %}">About Us</a></li>
            <li><a href="{% url 'blog:post_list' %}">Our Blog</a></li>
            <li><a href="{% url 'reservation:reserve_table' %}">Reserve A Table</a></li>
            <li><a href="{% url 'contact:c' %}">Contact</a></li>
          </ul>
        </div>
      </nav>

      <header class="site-header">
        <div class="row align-items-center">
          <div class="col-5 col-md-3">
             <ul class="list-unstyled social">
             <li><a href="https://www.facebook.com/"><span class="fa fa-facebook"></span></a></li>
              <li><a href="https://www.instagram.com/accounts/login/"><span class="fa fa-instagram"></span></a></li>
            </ul>
          </div>
          <div class="col-2 col-md-6 text-center">
            <a href="" class="site-logo">Bindu</a><br><br><br>
          </div>
          <div class="col-5 col-md-3 text-right menu-burger-wrap">
            <a href="#" class="site-nav-toggle js-site-nav-toggle"><i></i></a>

          </div>
        </div>
      </header> <!-- site-header -->


      {% block body %}

      {% endblock body %}
      <footer>
         <div class="img_bg" style="background-image: url({% static 'site_static/light.jpg' %})" data-stellar-background-ratio="0.5">

        <div class="site-footer">
          <div class="container">
            <div class="row small-gutters mb-5">
              <div class="col-md-5 col-lg-12 mb-100" data-aos="fade" data-aos-delay="100">
                <div class="footer-widget">
                  <h2><u>"Bindu Restaurant" : More than just a Restaurant:</u></h2><br>
                  <ul type="square">
                    <li>
                      <p class="lead"><u><b>Breakfast : </b></u> From hearty dishes to continental choices.Five styles of pancakes, seven styles of country breakfasts, seven choices of eggs Benedict — yet also featuring bowls and granola for lighter start-your-day meals.Traditional recipes, happily modified to suit your preferences. Serving until noon!</p>
                    </li>
                    <li>
                      <p class="lead"><u><b>Dinner : </b></u> Feel like locally sourced fresh fish and lobster? No problem.Or simply want a burger or pizza? We have you covered.With 38 mouth-watering dishes on our entry list alone,there’s something delicious for every member of your family. As one of our customers put it: “The worst thing I’ve ever tried here was delicious!”</p>
                    </li>
                    <li>
                      <p class="lead"><u><b>Bakery : </b></u> Right next door is our Hole in One bakery,for quick and easy take-out of super-fresh breakfast pastries, donuts and desserts.Managed by sister who have baked together for a quarter-century,our bakery also serves as the pastry kitchen — but is well worth a separate visit.The selections vary continuously!</p>
                    </li>
                  </ul><hr>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-6" data-aos="fade" data-aos-delay="100">
                <div class="footer-widget">
                  <h3><u>Lunch Service</u></h3>
                  <p>Booking from 12:00pm - 1:30pm</p>
                  <h3><u>Dinner Service</u></h3>
                  <p>Every Day: <br> Booking from 6:00pm - 9:00pm</p>
                </div>
              </div>
              <div class="col-md-1 col-lg-2 mb-1" data-aos="fade" data-aos-delay="100">
                <div class="footer-widget">
                  <h3><u>Quick Links</u></h3>
                  <ul>
                    <li><a href=http://127.0.0.1:8000/c>Help &amp; Support</a></li>
                    <li><a href="http://127.0.0.1:8000/c">Privacy Policy</a></li>
                    <li><a href="http://127.0.0.1:8000/c">Get in Touch</a></li>
                    <li><a href="http://127.0.0.1:8000/meals">Testimonials</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="200">
                <div class="footer-widget">
                  <h3><u>Subscribe</u></h3>
                  <p>Enjoy and Wait for Our New Recipy! </p>
                  <form action="" class="form-subscribe mb-5">
                    <div class="form-group form-field">
                      <input type="submit" value="Send" class="btn btn-primary">
                      <input type="text" class="form-control" placeholder="Email">
                    </div>
                  </form>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="100">
                <div class="footer-widget footer-contact-widget">
                  <h3><u>Contact Us</u></h3>
                  <p class="contact-email">info@binda.com</p>
                  <p class="contact-phone">91-797-5043-247</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </footer>
      <div class="site-footer-copyright">
        <div class="container">
          <div class="row">
             <p class="footer-text col-md-12">
               Copyright &copy;<script>document.write(new Date().getFullYear());</script>
               All rights reserved | Bindushree T S <i class="fa fa-heart" aria-hidden="true">
             </i> by <a href="http://127.0.0.1:8000" target="_blank">Bindushree</a></p>
          </div>
        </div>
      </div>
    </div>
    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>
    <script src="{% static 'site_static/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'site_static/js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'site_static/js/popper.min.js' %}"></script>
    <script src="{% static 'site_static/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'site_static/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'site_static/js/jquery.waypoints.min.js' %}"></script>

    <script src="{% static 'site_static/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'site_static/js/jquery.timepicker.min.js' %}"></script>
    <script src="{% static 'site_static/js/jquery.stellar.min.js' %}"></script>

    <script src="{% static 'site_static/js/aos.js' %}"></script>
    

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>

    <script src="{% static 'site_static/js/main.js' %}"></script>
  </body>
</html>